version = 1

[update]
autoupdate_label = "♻️ autoupdate"

[approve]
auto_approve_usernames = ["dependabot", "PeerRich", "baileypumfleet", "github-actions"]

[merge]
method = "squash"
automerge_label = ["i18n"]
