name: Add PRs to project

on:
  pull_request:
    types:
      - opened

jobs:
  add-PR-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/calcom/projects/1
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
