name: Submodule Sync
on:
  schedule:
    - cron: "15 */4 * * *"
  workflow_dispatch: ~
jobs:
  submodule-sync:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Git submodule update
        run: |
          git submodule update --remote --init
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
